services:

  tunnel:
    container_name: tunnel
    hostname: tunnel
    build: tunnel
    ports:
    - "0.0.0.0:8112:8112" # Deluge web client
    #- "0.0.0.0:58846:58846" # Deluge daemon
    - "0.0.0.0:9696:9696" # Prowlarr
    devices:
    - /dev/net/tun:/dev/net/tun
    env_file:
    - tunnel/.env
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

  preflight:
    container_name: preflight
    build:
      context: preflight
      additional_contexts:
        shared: shared
    volumes:
    - /srv/shared:/srv/shared
    env_file:
    - preflight/.env
    depends_on:
      tunnel:
        condition: service_healthy
    network_mode: "service:tunnel"

  monitor:
    container_name: monitor
    build:
      context: monitor
      additional_contexts:
        shared: shared
    env_file:
    - monitor/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    network_mode: "service:tunnel"
    healthcheck:
      test: ls /healthy
    restart: unless-stopped

  deluge:
    container_name: deluge
    build:
      context: deluge
      additional_contexts:
        shared: shared
      args:
        CROSS_SEED_API_KEY: ${CROSS_SEED_API_KEY}
    volumes:
    - /srv/deluge:/config
    - /srv/shared:/srv/shared
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      TZ: ${TIMEZONE}
    network_mode: "service:tunnel"
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8112 || exit 1
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    volumes:
    - /srv/prowlarr:/config
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      TZ: ${TIMEZONE}
    network_mode: "service:tunnel"
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:9696 || exit 1
    restart: unless-stopped

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6.0.0-36
    user: "${USER_ID}:${GROUP_ID}"
    container_name: cross-seed
    volumes:
    - /srv/cross-seed/config:/config
    - /srv/cross-seed/data:/cross-seeds
    - /srv/deluge/state:/torrents:ro
    - /srv/shared:/srv/shared
    command: >
      daemon
      --torznab ${CROSS_SEED_TORZNAB}
      --deluge-rpc-url ${CROSS_SEED_DELUGE_RPC_URL}
      --api-key ${CROSS_SEED_API_KEY}
      --torrent-dir /torrents
      --include-single-episodes true
    network_mode: "service:tunnel"
    depends_on:
      deluge:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    restart: no
