services:

  tunnel:
    container_name: tunnel
    hostname: tunnel
    image: ghcr.io/qdm12/gluetun
    ports:
    - "0.0.0.0:8112:8112" # Deluge web client
    #- "0.0.0.0:58846:58846" # Deluge daemon
    devices:
    - /dev/net/tun:/dev/net/tun
    env_file:
    - tunnel/.env
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

  preflight:
    container_name: preflight
    build: preflight
    volumes:
    - /srv/shared:/srv/shared:z
    env_file:
    - preflight/.env
    depends_on:
      tunnel:
        condition: service_healthy
    network_mode: "service:tunnel"

  monitor:
    container_name: monitor
    build: monitor
    env_file:
    - monitor/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    network_mode: "service:tunnel"
    healthcheck:
      test: ls /healthy
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge
    volumes:
    - /srv/deluge:/config:Z
    - /srv/shared:/srv/shared:z
    network_mode: "service:tunnel"
    depends_on:
      preflight:
        condition: service_completed_successfully
    env_file:
    - .env
    healthcheck:
      test: curl --fail http://localhost:8112 || exit 1
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    volumes:
    - /srv/prowlarr:/config:Z
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    network_mode: "service:tunnel"
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:9696 || exit 1
    restart: unless-stopped

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6.0.0-27
    container_name: cross-seed
    user: 1000:1000
    volumes:
    - /srv/cross-seed/config:/config:Z
    - /srv/cross-seed/data:/cross-seeds:Z
    - /srv/deluge/state:/torrents:Z
    - /srv/shared:/srv/shared:z
    command: daemon
    depends_on:
    - deluge
    - prowlarr
    restart: no
