#!/bin/bash

RETRY=${RETRY:-"2s"}
INTERVAL=${INTERVAL:-"5m"}

source ./logging

failed-wait-and-retry() {
  if [[ -f /healthy ]]
  then
    rm /healthy
  fi
  log-debug "${BOLD}Retrying${RESET} in ${RETRY}"
  sleep "${RETRY}"
}

success-wait() {
  touch /healthy
  log-debug "${BOLD}Waiting${RESET} ${INTERVAL} before next run"
  sleep "${INTERVAL}"
}

# Validate environment variables
ISSUES=()
if [[ -z "${GLUETUN_API_PORT}" ]]
then
  GLUETUN_API_PORT=${GLUETUN_API_PORT:-"8000"}
  log-information "GLUETUN_API_PORT is not set. Defaulting to ${GLUETUN_API_PORT}"
fi
if [[ -z "${QBIT_WEB_PORT}" ]]
then
  QBIT_WEB_PORT=${QBIT_WEB_PORT:-"8080"}
  log-information "QBIT_WEB_PORT is not set. Defaulting to ${QBIT_WEB_PORT}"
fi
if [[ -z "${QBIT_USER}" ]]
then
  ISSUES+=("QBIT_USER")
fi
if [[ -z "${QBIT_PASSWORD}" ]]
then
  ISSUES+=("QBIT_PASSWORD")
fi
if [[ "${#ISSUES[@]}" -gt 0 ]]
then
  log-error "Missing environment variables: ${ISSUES[*]}"
  log-critical "Unable to continue"
  sleep infinity
fi

while true
do
  log-information "${BOLD}Running${RESET} monitor"

  log-debug "${BOLD}Determining${RESET} forwarded port"
  JSON=$(curl --fail --silent --show-error "http://localhost:${GLUETUN_API_PORT}/v1/openvpn/portforwarded")
  PORT=$(echo "${JSON}" | jq -r '.port')
  if [[ "${PORT}" == "" ]]
  then
    log-error "Forwarded port is not defined"
    failed-wait-and-retry
    continue
  elif [[ -f /port && $(cat /port) == "${PORT}" ]]
  then
    log-debug "Port is already set to ${PORT}"
    success-wait
    continue
  fi

  log-debug "${BOLD}Authenticating${RESET} with API"
  if ! curl --fail-with-body --silent \
    --data "username=${QBIT_USER}" \
    --data "password=${QBIT_PASSWORD}" \
    --cookie-jar /tmp/deluge-cookie \
    "http://localhost:${QBIT_WEB_PORT}/api/v2/auth/login"
  then
    log-error "${BOLD}Failed${RESET} to authenticate"
    log-trace "${JSON}"
    failed-wait-and-retry
    continue
  fi

  log-debug "${BOLD}Setting${RESET} listen port"
  if ! curl --fail-with-body --silent \
    --cookie /tmp/deluge-cookie \
    --data-urlencode "json={\"listen_port\": ${PORT}}" \
    "http://localhost:${QBIT_WEB_PORT}/api/v2/app/setPreferences"
  then
    log-trace "${JSON}"
    failed-wait-and-retry
    continue
  fi

  log-success "${BOLD}Set${RESET} listen port to ${PORT}"
  touch /port
  echo "${PORT}" > /port
  success-wait
  continue
done

echo "Service terminated"

exit 1
